export const crystalForgeAbi = [
  {
    type: "event",
    name: "ForgeRequested",
    inputs: [
      { type: "address", name: "player", indexed: true },
      { type: "uint256", name: "requestId", indexed: true },
      { type: "uint256", name: "paid", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrystalForged",
    inputs: [
      { type: "address", name: "player", indexed: true },
      { type: "uint8", name: "result", indexed: false },
      { type: "uint256", name: "payout", indexed: false },
      { type: "uint256", name: "playIndex", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ForgeRefunded",
    inputs: [
      { type: "address", name: "player", indexed: true },
      { type: "uint256", name: "requestId", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "PLAY_COST",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalPlays",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalBurned",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalPaidOut",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "nextRequestId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "playerPlays",
    stateMutability: "view",
    inputs: [{ type: "address", name: "player" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "playerWinnings",
    stateMutability: "view",
    inputs: [{ type: "address", name: "player" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "pendingForges",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [
      { type: "address", name: "player" },
      { type: "uint256", name: "paid" },
      { type: "uint256", name: "requestBlock" },
      { type: "bool", name: "settled" },
    ],
  },
  {
    type: "function",
    name: "getRecentHistory",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "count" }],
    outputs: [
      {
        type: "tuple[]",
        name: "",
        components: [
          { type: "address", name: "player" },
          { type: "uint8", name: "result" },
          { type: "uint256", name: "payout" },
          { type: "uint256", name: "timestamp" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "forge",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ type: "uint256", name: "requestId" }],
  },
  {
    type: "function",
    name: "settleForge",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundExpiredForge",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [],
  },
] as const;
