export const frxLotteryAbi = [
  {
    type: "event",
    name: "EnteredLottery",
    inputs: [
      { type: "address", name: "player", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
      { type: "uint256", name: "round", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WinnerDrawn",
    inputs: [
      { type: "uint256", name: "round", indexed: false },
      { type: "address", name: "winner", indexed: true },
      { type: "uint256", name: "prize", indexed: false },
      { type: "uint256", name: "treasury", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "MIN_ENTRY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "DRAW_INTERVAL",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "MAX_ENTRIES_PER_ROUND",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "currentRound",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "lastDrawTime",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "currentPool",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "timeUntilDraw",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "currentEntryCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "getRoundEntries",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "round" }],
    outputs: [
      {
        type: "tuple[]",
        name: "",
        components: [
          { type: "address", name: "player" },
          { type: "uint256", name: "amount" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "roundWinner",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "round" }],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "roundPrize",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "round" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "enter",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "amount" }],
    outputs: [],
  },
  {
    type: "function",
    name: "drawWinner",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
] as const;
