export const frxStakingAbi = [
  {
    type: "event",
    name: "Staked",
    inputs: [
      { type: "address", name: "owner", indexed: true },
      { type: "uint256", name: "tokenId", indexed: false },
      { type: "uint8", name: "rarity", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unstaked",
    inputs: [
      { type: "address", name: "owner", indexed: true },
      { type: "uint256", name: "tokenId", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { type: "address", name: "owner", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "BASE_RATE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "rarityMultiplier",
    stateMutability: "view",
    inputs: [{ type: "uint8", name: "rarity" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "stakes",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "tokenId" }],
    outputs: [
      { type: "address", name: "owner" },
      { type: "uint256", name: "stakedAt" },
      { type: "uint256", name: "lastClaimed" },
      { type: "uint8", name: "rarity" },
    ],
  },
  {
    type: "function",
    name: "stake",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "tokenId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unstake",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "tokenId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "tokenId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimAll",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "pendingRewards",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "tokenId" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalPendingRewards",
    stateMutability: "view",
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "getStakedTokens",
    stateMutability: "view",
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "uint256[]", name: "" }],
  },
  {
    type: "function",
    name: "effectivePassHolder",
    stateMutability: "view",
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "hasStakedPass",
    stateMutability: "view",
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "bool", name: "" }],
  },
] as const;
